#!/bin/sh
set -e

DEV_VARS_FILE="/app/dist/server/.dev.vars"
VAR_NAMES="SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY PUBLIC_SUPABASE_ANON_KEY UPSTASH_REDIS_REST_URL UPSTASH_REDIS_REST_TOKEN TMDB_API_KEY TMDB_ACCESS_TOKEN CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN"
HAS_VARS=0

# Validate required vars
if [ -z "$SUPABASE_URL" ]; then
  echo "ERROR: SUPABASE_URL is not set. The application will not function without it." >&2
  exit 1
fi

for name in $VAR_NAMES; do
  eval "value=\$$name"
  if [ -n "$value" ]; then
    HAS_VARS=1
    break
  fi
done

if [ "$HAS_VARS" = "1" ]; then
  # Clean any stale .dev.vars before regeneration
  rm -f "$DEV_VARS_FILE"
  echo "# Generated by docker-entrypoint.sh" > "$DEV_VARS_FILE"
  for name in $VAR_NAMES; do
    eval "value=\$$name"
    if [ -n "$value" ]; then
      echo "$name=$value" >> "$DEV_VARS_FILE"
    fi
  done
  echo "wrangler: generated .dev.vars from container environment" >&2
fi

exec "$@"
